### ISSUE TITLE
Edge is throwing SyntaxError in MutationObserver.observe

### ISSUE THREAD

**Issue by eky** [WebReflection/built-in-element#1]
https://github.com/WebReflection/built-in-element/blob/d2e17e31edf0d53ecfd9f0bebc2d67e6926da4d0/index.js#L51

Edge (and IE 11) requires to set option `attributes` to `true`.
Please change to
`{attributes: true, attributeFilter: oa, attributeOldValue: true}`
to make Edge works.

**Comment by WebReflection** [comment]
I don't think it's clear this polyfill patches only browsers with `customElements`, which means neither IE11 nor Edger should actually touch it if you use `document-register-element` upfront as explained in the readme.

**Comment by WebReflection** [comment]
As you can see (but you could've seen that before too) IE11, as well as Edge, already work.
https://webreflection.github.io/built-in-element/test/es5/

Regardless, I have added `attributes: true` for those using unsupported polyfills upfront.

<img width="479" alt="screen shot 2018-11-09 at 09 40 52" src="https://user-images.githubusercontent.com/85749/48252021-d71f7d00-e403-11e8-97a3-690cb851e982.png">
