### ISSUE TITLE
Mutation Observer: new elements that appear because of outerHTML aren't set up

### ISSUE THREAD

**Issue by baldurbjarnason** [WebReflection/built-in-element#2]
Before I get to the bug: love your open source work ❤️ 

## The issue: 

When a parent element is replaced  using `outerHTML` only the parent element appears as a change in the Mutation Observer callback, not its children. So if the changed element now has new elements with the `is` attribute those elements aren't set up in the Mutation Observer callback and never get connected.

And similarly previously upgraded elements that are removed this way don't get disconnected properly.

The way I fixed the issue in the project I'm working on was by adding the following after the `setupIfNeeded(addedNodes[j])` line in the Mutation Observer:

```
if (addedNodes[j].querySelectorAll) {
    addedNodes[j].querySelectorAll('[is]').forEach(node => {
          setupIfNeeded(node)
    })
}
```

And then something similar for disconnecting in the removedNodes block later.

Not proposing you fix it this way. I'm sure there are better ways of solving this problem. I only needed to get things working in a quick prototype I'm making 🙂 

## Tested in

Safari. Most of the other browsers we're targeting either support built-ins or don't support custom elements at all (and so get the `document-register-element` polyfill instead).

**Comment by WebReflection** [comment]
I think I saw this coming, and I was just not remembering the use case for this, but I've solved it the same for _DRE_ poly ...

So ... do you mind testing this file and tell me if everything works for you?
https://github.com/WebReflection/built-in-element/blob/nested-nodes-upgrade/min.js

Thanks.

**Comment by baldurbjarnason** [comment]
Yup. That file works for me. 👍
